#!/usr/bin/env python
"""
Facebook Comment Monitor
Continuously monitors Facebook posts for new comments and creates action files
"""

import sys
import time
import json
from pathlib import Path
from datetime import datetime, timedelta

# Add facebook folder to path
facebook_path = Path(__file__).parent.parent / 'facebook'
sys.path.insert(0, str(facebook_path))

# Load environment
from dotenv import load_dotenv
env_file = facebook_path / '.env'
if env_file.exists():
    load_dotenv(env_file)
else:
    print(f"✗ .env file not found at {env_file}")
    sys.exit(1)

from facebook_graph_mcp_server import facebook_client

# Configuration
CHECK_INTERVAL = 60  # Check every 60 seconds
KEYWORDS = {
    'urgent': ['urgent', 'asap', 'emergency', 'immediately', 'right now'],
    'sales': ['price', 'pricing', 'cost', 'quote', 'invoice', 'buy', 'purchase'],
    'support': ['help', 'support', 'issue', 'problem', 'broken', 'not working'],
    'question': ['question', 'how', 'what', 'when', 'where', 'why', 'can you', 'do you']
}
VAULT_PATH = Path(__file__).parent / 'AI_Employee_Vault'
NEEDS_ACTION = VAULT_PATH / 'Needs_Action'
LOGS_PATH = VAULT_PATH / 'Logs'

# Ensure folders exist
NEEDS_ACTION.mkdir(parents=True, exist_ok=True)
LOGS_PATH.mkdir(parents=True, exist_ok=True)

# Track processed comments
processed_comments = set()
last_check_time = datetime.now()

def categorize_comment(message):
    """Categorize comment based on keywords"""
    message_lower = message.lower()
    categories = []
    
    for category, keywords in KEYWORDS.items():
        if any(kw in message_lower for kw in keywords):
            categories.append(category)
    
    return categories if categories else ['general']

def get_priority(categories):
    """Get priority based on categories"""
    if 'urgent' in categories:
        return 'CRITICAL'
    elif 'sales' in categories:
        return 'HIGH'
    elif 'support' in categories:
        return 'MEDIUM'
    else:
        return 'LOW'

def create_action_file(post, comment, categories):
    """Create action file in Needs_Action folder"""
    priority = get_priority(categories)
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    
    filename = f"FACEBOOK_COMMENT_{timestamp}_{comment['id'][:8]}.md"
    filepath = NEEDS_ACTION / filename
    
    content = f"""---
type: facebook_comment
post_id: {post['id']}
comment_id: {comment['id']}
from: {comment['from']}
received: {datetime.now().isoformat()}
priority: {priority.lower()}
categories: {', '.join(categories)}
---

# Facebook Comment Requires Attention

## Comment Details
- **Post ID:** {post['id']}
- **Comment ID:** {comment['id']}
- **From:** {comment['from']}
- **Received:** {comment['created_time']}
- **Priority:** {priority}
- **Categories:** {', '.join(categories)}

## Comment Message
{comment['message']}

## Post Context
{post.get('message', 'No message')[:200]}...

## Suggested Actions
- [ ] Review the comment
- [ ] Draft appropriate response
- [ ] Post response using Facebook MCP
- [ ] Follow up if needed
- [ ] Archive after processing

## Quick Response Commands

### Using Qwen Code
```bash
qwen "Draft a professional response to this Facebook comment: {comment['message'][:100]}"
```

### Post Response via MCP
```bash
python -m facebook_graph_mcp_server --tool facebook_create_comment \\
  --args '{{\"post_id\": \"{post['id']}\", \"message\": \"Your response here\"}}'
```

### Post Response via Python
```python
from facebook_graph_mcp_server import facebook_client
facebook_client.create_comment("{post['id']}", "Your response here")
```

## Response Guidelines
- **Urgent:** Respond within 1 hour
- **Sales:** Respond within 4 hours
- **Support:** Respond within 24 hours
- **General:** Respond within 48 hours

---
*Generated by Facebook Comment Monitor - Gold Tier*
"""
    
    filepath.write_text(content, encoding='utf-8')
    return filepath

def log_activity(activity_type, data):
    """Log activity to JSONL file"""
    log_file = LOGS_PATH / f"facebook_activity_{datetime.now().strftime('%Y%m%d')}.jsonl"
    
    entry = {
        'timestamp': datetime.now().isoformat(),
        'type': activity_type,
        'data': data
    }
    
    with open(log_file, 'a') as f:
        f.write(json.dumps(entry) + '\n')

def monitor_comments():
    """Main monitoring loop"""
    global last_check_time, processed_comments
    
    print("\n" + "=" * 60)
    print("  Facebook Comment Monitor - Gold Tier")
    print("=" * 60)
    print(f"\n  Started: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"  Check Interval: {CHECK_INTERVAL} seconds")
    print(f"  Monitoring Keywords: {', '.join([kw for kws in KEYWORDS.values() for kw in kws][:10])}...")
    print(f"  Action Folder: {NEEDS_ACTION}")
    print("\n  Press Ctrl+C to stop\n")
    
    # Get initial posts to monitor
    print("Loading recent posts to monitor...")
    try:
        posts = facebook_client.get_posts(limit=10)
        print(f"✓ Monitoring {len(posts)} recent posts\n")
    except Exception as e:
        print(f"✗ Failed to load posts: {e}")
        return
    
    check_count = 0
    
    while True:
        check_count += 1
        check_time = datetime.now()
        
        print(f"[{check_time.strftime('%H:%M:%S')}] Check #{check_count}...")
        
        for post in posts:
            try:
                # Get comments on post
                comments = facebook_client.get_comments(post['id'], limit=50)
                
                for comment in comments:
                    comment_id = comment['id']
                    
                    # Skip if already processed
                    if comment_id in processed_comments:
                        continue
                    
                    # Check if comment is new (since last check)
                    try:
                        comment_time = datetime.fromisoformat(
                            comment['created_time'].replace('Z', '+00:00')
                        ).replace(tzinfo=None)
                        
                        if comment_time <= last_check_time:
                            continue
                    except:
                        pass  # Include comment if time parsing fails
                    
                    # Process new comment
                    processed_comments.add(comment_id)
                    
                    # Categorize comment
                    categories = categorize_comment(comment['message'])
                    priority = get_priority(categories)
                    
                    print(f"  📌 New comment from {comment['from']}")
                    print(f"     Priority: {priority}")
                    print(f"     Categories: {', '.join(categories)}")
                    print(f"     Message: {comment['message'][:60]}...")
                    
                    # Create action file for non-general comments
                    if priority != 'LOW' or len(categories) > 0:
                        action_file = create_action_file(post, comment, categories)
                        print(f"     ✓ Created action file: {action_file.name}")
                        
                        # Log activity
                        log_activity('comment_detected', {
                            'comment_id': comment_id,
                            'post_id': post['id'],
                            'from': comment['from'],
                            'priority': priority,
                            'categories': categories,
                            'action_file': str(action_file)
                        })
                    
            except Exception as e:
                print(f"  ✗ Error checking post {post['id']}: {e}")
        
        # Also check notifications
        try:
            notifications = facebook_client.get_notifications(limit=20)
            new_notifications = [n for n in notifications 
                                if n['id'] not in processed_comments]
            
            for notif in new_notifications[:5]:  # Process top 5 new notifications
                processed_comments.add(notif['id'])
                
                # Check if notification is important
                message = notif.get('message', '').lower()
                if any(kw in message for kws in KEYWORDS.values() for kw in kws):
                    print(f"  🔔 Important notification: {notif.get('from', 'Unknown')}")
                    log_activity('important_notification', {
                        'notification_id': notif['id'],
                        'from': notif.get('from'),
                        'message': notif.get('message')
                    })
            
        except Exception as e:
            print(f"  ✗ Error checking notifications: {e}")
        
        # Update last check time
        last_check_time = check_time
        
        # Wait for next check
        time.sleep(CHECK_INTERVAL)

def main():
    """Main entry point"""
    print("\n✓ Facebook Comment Monitor")
    print(f"  Connected to: {facebook_client.page_id or 'User Profile'}")
    
    # Verify connection
    try:
        token_info = facebook_client.verify_token()
        if not token_info.get('valid'):
            print("✗ Facebook token is invalid!")
            print("  Please update your token in facebook/.env")
            return
        print("✓ Facebook token is valid\n")
    except Exception as e:
        print(f"✗ Token verification failed: {e}")
        return
    
    try:
        monitor_comments()
    except KeyboardInterrupt:
        print("\n\n⚠️  Monitoring stopped by user")
        print(f"\nSummary:")
        print(f"  Total checks: {check_count if 'check_count' in locals() else 0}")
        print(f"  Comments tracked: {len(processed_comments)}")
        print(f"  Action files created: {len(list(NEEDS_ACTION.glob('FACEBOOK_COMMENT_*.md')))}")
    except Exception as e:
        print(f"\n✗ Error: {e}")

if __name__ == "__main__":
    check_count = 0
    main()
