#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Approval Workflow Manager - Human-in-the-Loop approval system.

Manages approval requests in /Pending_Approval, processes approved items,
handles expirations, and maintains audit logs.

Usage:
    python approval_manager.py /path/to/vault --check
    python approval_manager.py /path/to/vault --process-approved
"""

import sys
import json
import logging
import argparse
from pathlib import Path
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Any
import re

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)


class ApprovalManager:
    """Manage human-in-the-loop approval workflow."""
    
    def __init__(self, vault_path: Path):
        """
        Initialize Approval Manager.
        
        Args:
            vault_path: Path to Obsidian vault
        """
        self.vault = vault_path
        self.pending = vault_path / 'Pending_Approval'
        self.approved = vault_path / 'Approved'
        self.rejected = vault_path / 'Rejected'
        self.done = vault_path / 'Done'
        self.logs = vault_path / 'Logs'
        self.plans = vault_path / 'Plans'
        
        # Ensure directories exist
        for folder in [self.pending, self.approved, self.rejected, self.done, self.logs]:
            folder.mkdir(parents=True, exist_ok=True)
        
        self.logger = logging.getLogger(self.__class__.__name__)
    
    def create_approval_request(self, action_type: str, details: Dict[str, Any],
                                reason: str, priority: str = 'normal',
                                expires_hours: int = 24) -> Path:
        """
        Create approval request file.
        
        Args:
            action_type: Type of action (email_send, payment, social_post, etc.)
            details: Action-specific details
            reason: Why approval is required
            priority: 'low', 'normal', 'high', 'urgent'
            expires_hours: Hours until expiration
            
        Returns:
            Path to created file
        """
        now = datetime.now()
        expires = now + timedelta(hours=expires_hours)
        timestamp = int(now.timestamp())
        
        # Build details section
        details_md = self._format_details(details)
        
        # Determine filename
        filename = f'APPROVAL_{action_type}_{timestamp}.md'
        
        content = f'''---
type: approval_request
action: {action_type}
created: {now.isoformat()}
expires: {expires.isoformat()}
status: pending
priority: {priority}
---

# Approval Required: {self._format_action_name(action_type)}

## Details

{details_md}

## Why Approval Required

{reason}

---

## To Approve

Move this file to `/Approved` folder.

## To Reject

Move this file to `/Rejected` folder and add a comment explaining why.

---

## Expiration

This approval request expires on **{expires.strftime('%Y-%m-%d at %H:%M')}**.

Expired requests will be automatically rejected.

---
*Generated by Approval Manager v0.1 (Silver Tier)*
'''
        filepath = self.pending / filename
        filepath.write_text(content)
        
        self.logger.info(f"Created approval request: {filename}")
        self._log_action('approval_created', str(filepath), {'action_type': action_type, 'priority': priority})
        
        return filepath
    
    def check_expirations(self) -> List[Path]:
        """
        Check for expired approvals and move to Rejected.
        
        Returns:
            List of expired file paths
        """
        expired = []
        
        for filepath in self.pending.glob('*.md'):
            content = filepath.read_text()
            
            # Parse expiration from frontmatter
            expires = self._parse_expiration(content)
            
            if expires and datetime.now() > expires:
                # Add expiration notice
                updated_content = content + f'\n\n**⚠️ EXPIRED:** {expires.isoformat()}\n\nThis request was automatically rejected due to expiration.'
                filepath.write_text(updated_content)
                
                # Move to Rejected
                dest = self.rejected / filepath.name
                filepath.rename(dest)
                expired.append(dest)
                
                self.logger.warning(f"Approval expired: {filepath.name}")
                self._log_action('approval_expired', str(filepath))
        
        if expired:
            self.logger.info(f"Moved {len(expired)} expired approvals to Rejected")
        
        return expired
    
    def process_approved(self, execute_callback=None) -> List[Dict]:
        """
        Process all approved actions.
        
        Args:
            execute_callback: Optional function to execute actions
                             Signature: callback(filepath, action_type, details) -> result
            
        Returns:
            List of execution results
        """
        results = []
        
        for filepath in self.approved.glob('*.md'):
            self.logger.info(f"Processing approved: {filepath.name}")
            
            try:
                # Read and parse
                content = filepath.read_text()
                action_type = self._extract_field(content, 'action')
                details = self._extract_details(content)
                
                # Execute action
                if execute_callback:
                    result = execute_callback(filepath, action_type, details)
                else:
                    result = {'status': 'pending_external', 'action': action_type}
                
                result['file'] = str(filepath)
                result['action_type'] = action_type
                results.append(result)
                
                # Move to Done
                dest = self.done / filepath.name
                filepath.rename(dest)
                
                self.logger.info(f"Processed: {filepath.name} -> {dest.name}")
                self._log_action('approval_processed', str(filepath), result)
                
            except Exception as e:
                self.logger.error(f"Error processing {filepath.name}: {e}")
                results.append({
                    'file': str(filepath),
                    'status': 'error',
                    'error': str(e)
                })
        
        return results
    
    def reject_with_comment(self, filepath: Path, comment: str) -> Path:
        """
        Reject an approval with a comment.
        
        Args:
            filepath: Path to approval file
            comment: Reason for rejection
            
        Returns:
            New path in Rejected folder
        """
        content = filepath.read_text()
        updated = content + f'\n\n**REJECTED:** {datetime.now().isoformat()}\n\n**Reason:** {comment}'
        filepath.write_text(updated)
        
        dest = self.rejected / filepath.name
        filepath.rename(dest)
        
        self.logger.info(f"Rejected: {filepath.name} - {comment}")
        self._log_action('approval_rejected', str(filepath), {'reason': comment})
        
        return dest
    
    def get_pending_count(self) -> int:
        """Get count of pending approvals."""
        return len(list(self.pending.glob('*.md')))
    
    def get_approved_count(self) -> int:
        """Get count of approved items ready to process."""
        return len(list(self.approved.glob('*.md')))
    
    def list_pending(self) -> List[Dict]:
        """List all pending approvals with metadata."""
        pending = []
        
        for filepath in sorted(self.pending.glob('*.md')):
            content = filepath.read_text()
            pending.append({
                'file': filepath.name,
                'path': str(filepath),
                'action': self._extract_field(content, 'action'),
                'created': self._extract_field(content, 'created'),
                'expires': self._extract_field(content, 'expires'),
                'priority': self._extract_field(content, 'priority', 'normal')
            })
        
        return pending
    
    def _format_details(self, details: Dict[str, Any]) -> str:
        """Format details dict as markdown table."""
        lines = ['| Field | Value |', '|-------|-------|']
        
        for key, value in details.items():
            formatted_key = key.replace('_', ' ').title()
            formatted_value = str(value)
            if len(formatted_value) > 100:
                formatted_value = formatted_value[:97] + '...'
            lines.append(f'| {formatted_key} | {formatted_value} |')
        
        return '\n'.join(lines)
    
    def _format_action_name(self, action_type: str) -> str:
        """Format action type as readable name."""
        return action_type.replace('_', ' ').title()
    
    def _parse_expiration(self, content: str) -> Optional[datetime]:
        """Parse expiration datetime from content."""
        match = re.search(r'expires:\s*(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2})', content)
        if match:
            try:
                return datetime.fromisoformat(match.group(1))
            except ValueError:
                pass
        return None
    
    def _extract_field(self, content: str, field: str, default: str = '') -> str:
        """Extract field from YAML frontmatter."""
        match = re.search(rf'{field}:\s*(.+)', content)
        if match:
            return match.group(1).strip()
        return default
    
    def _extract_details(self, content: str) -> Dict[str, str]:
        """Extract details from approval file."""
        details = {}
        
        # Simple extraction - look for content between ## Details and next ##
        match = re.search(r'## Details\s*\n(.*?)\n##', content, re.DOTALL)
        if match:
            table = match.group(1)
            # Parse markdown table
            lines = table.strip().split('\n')[2:]  # Skip header and separator
            for line in lines:
                if '|' in line:
                    parts = line.split('|')
                    if len(parts) >= 3:
                        key = parts[1].strip().lower().replace(' ', '_')
                        value = parts[2].strip()
                        details[key] = value
        
        return details
    
    def _log_action(self, action_type: str, details: str, extra: Dict = None):
        """Log action for audit trail."""
        today = datetime.now().strftime('%Y-%m-%d')
        log_file = self.logs / f'{today}_approvals.jsonl'
        
        entry = {
            'timestamp': datetime.now().isoformat(),
            'action': action_type,
            'details': details
        }
        
        if extra:
            entry.update(extra)
        
        try:
            with open(log_file, 'a') as f:
                f.write(json.dumps(entry) + '\n')
        except Exception as e:
            self.logger.error(f"Failed to log action: {e}")


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(description='Approval Workflow Manager')
    parser.add_argument('vault_path', help='Path to Obsidian vault')
    parser.add_argument('--check', '-c', action='store_true',
                       help='Check for expired approvals')
    parser.add_argument('--process-approved', '-p', action='store_true',
                       help='Process approved items')
    parser.add_argument('--list', '-l', action='store_true',
                       help='List pending approvals')
    parser.add_argument('--stats', '-s', action='store_true',
                       help='Show approval statistics')
    parser.add_argument('--create', help='Create test approval request')
    
    args = parser.parse_args()
    
    vault_path = Path(args.vault_path)
    if not vault_path.exists():
        print(f"Error: Vault path does not exist: {vault_path}")
        sys.exit(1)
    
    manager = ApprovalManager(vault_path)
    
    if args.check:
        expired = manager.check_expirations()
        if expired:
            print(f"Expired approvals moved to Rejected: {len(expired)}")
        else:
            print("No expired approvals found.")
    
    elif args.process_approved:
        results = manager.process_approved()
        print(f"Processed {len(results)} approved items:")
        for result in results:
            print(f"  - {result['file']}: {result.get('status', 'unknown')}")
    
    elif args.list:
        pending = manager.list_pending()
        if pending:
            print(f"Pending approvals ({len(pending)}):")
            for item in pending:
                priority = item.get('priority', 'normal')
                print(f"  [{priority.upper()}] {item['file']}")
                print(f"         Action: {item['action']}")
                print(f"         Expires: {item['expires']}")
        else:
            print("No pending approvals.")
    
    elif args.stats:
        pending_count = manager.get_pending_count()
        approved_count = manager.get_approved_count()
        rejected_count = len(list(manager.rejected.glob('*.md')))
        done_count = len(list(manager.done.glob('APPROVAL_*.md')))
        
        print("Approval Statistics:")
        print(f"  Pending:   {pending_count}")
        print(f"  Approved:  {approved_count}")
        print(f"  Rejected:  {rejected_count}")
        print(f"  Completed: {done_count}")
    
    elif args.create:
        # Create test approval request
        filepath = manager.create_approval_request(
            action_type='test_action',
            details={'test': 'value', 'description': 'This is a test approval request'},
            reason='Testing the approval workflow system',
            priority='normal',
            expires_hours=24
        )
        print(f"Created test approval: {filepath.name}")
    
    else:
        parser.print_help()
        print("\nExamples:")
        print("  # Check for expired approvals")
        print("  python approval_manager.py ./vault --check")
        print()
        print("  # Process approved items")
        print("  python approval_manager.py ./vault --process-approved")
        print()
        print("  # List pending approvals")
        print("  python approval_manager.py ./vault --list")
        print()
        print("  # Create test approval")
        print("  python approval_manager.py ./vault --create")


if __name__ == '__main__':
    main()
